config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users, :except => [:index]
  resources :rounds
  resources :guesses

  root 'deck#index'

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :deck
  has_many :guesses
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  has_many :rounds
  has_many :cards
end

app/models/guess.rb
class Guess < ActiveRecord::Base
  belongs_to :user
  belongs_to :round
  belongs_to :card
end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :user
  belongs_to :deck
  has_many :guesses

  def next_card
  	set = self.deck.cards - correctly_guessed_cards
  	set.sample
  end

  def correctly_guessed_cards
  	self.guesses.where(is_correct: true).collect { |guess| guess.card}
  end

  def first_guess
    false_array = self.guesses.select { |guess| guess.is_correct == false }
    unique_guesses = self.guesses
    self.guesses.each do |guess|
      false_array.each do |false_guess|
        if guess.card_id == false_guess.card_id
          unique_guesses -= [guess]
        end
      end
    end
    unique_guesses.length
  end
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	validates :password, :email, presence: true
	validates :email, uniqueness: true
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
	
	has_many :rounds
    has_many :guesses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include SessionsHelper
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	def show
	    @card = Card.find_by(id: params[:id])
		@round = Round.find_by(id: params[:captures][0])
  		render 'cards/show'
	end
end

app/controllers/deck_controller.rb
class DeckController < ApplicationController

	def index
		@decks = Deck.all
		render 'index'
	end

end

app/controllers/guess_controller.rb
class GuessController < ApplicationController

	def create
		submitted_answer = Card.find_by(id: params[:card_id])
		if submitted_answer.answer.downcase == params[:response].downcase
		    correct = true
		else
		    correct = false
		end

		if logged_in?
		    @guess = Guess.create(user_id: current_user.id, round_id: params[:round_id], card_id: params[:card_id], response: params[:response], is_correct: correct)
	    else
		    @guess = Guess.create(round_id: params[:round_id], card_id: params[:card_id], response: params[:response], is_correct: correct)
		end

		@round = Round.find_by(id: params[:round_id])
		@card = @round.next_card

	    if @card
		    erb :"cards/show"
	    else
		    redirect "/rounds/#{@round.id}"
	    end
	end


end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController

	def create
		submitted_answer = Card.find_by(id: params[:card_id])
		if submitted_answer.answer.downcase == params[:'/guesses'][:response].downcase
		    correct = true
		else
		    correct = false
		end

		if logged_in?
		    @guess = Guess.create(user_id: current_user.id, round_id: params[:round_id], card_id: params[:card_id], response: params[:response], is_correct: correct)
	    else
		    @guess = Guess.create(round_id: params[:round_id], card_id: params[:card_id], response: params[:response], is_correct: correct)
		end

		@round = Round.find_by(id: params[:round_id])
		@card = @round.next_card

	    if @card
		    render "cards/show"
	    else
		    redirect_to "/rounds/#{@round.id}"
	    end
	end

end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
	
	def create
		if logged_in?
			@round = Round.create(user_id: current_user.id, deck_id: params[:deck_id])
		else
			@round = Round.create(deck_id: params[:deck_id])
		end
		@card_deck = @round.deck.cards.shuffle
		@card = @card_deck[0]
		render 'cards/show'
	end

	def show
    	@round = Round.find_by(id: params[:id])
		if @round
		    @round_category = @round.deck.category
		    @total_guesses = @round.guesses.length
		    @total_questions = @round.deck.cards.length
		    @first_try = @round.first_guess
		    render '/rounds/show'
		else
		    redirect_to '/'
		end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
 	  user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in(user)
  		redirect_to user
  	else
  		flash.now[:danger] = 'Invalid email/password combination'
  		render 'new'
  	end
  end

  def destroy
  	session.delete(:user_id)
  	redirect_to	root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  	@user = User.new
  end

  def show
  	@user = User.find_by(id: params[:id])
  	@email = @user.email
    @rounds = @user.rounds
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      log_in(@user)
  		redirect_to @user
  	else
  		@errors = @user.errors.full_messages
  		render 'new'
  	end
  end


private

	def user_params
		params.require(:user).permit(:email, :password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/deck_helper.rb
module DeckHelper
end

app/helpers/guesses_helper.rb
module GuessesHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def logged_in?
		!current_user.nil?
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cards/show.html.erb
<h2><%= @card.deck.category %></h2>


<h4><%= @card.question %></h4>

<h3>Enter your guess:</h3>

<%= form_for guesses_path, :url => guesses_path, :html => { :method => :post} do |f| %>
	<%= hidden_field_tag(:card_id, value=@card.id)%>
	<%= hidden_field_tag(:round_id, value=@round.id)%>
	<%= f.text_field :response, placeholder: "answer" %>
	<%= f.submit "answer" %>
<% end %>

app/views/deck/index.html.erb
<h1>Flash-Stach!</h1>

<ul>
<% @decks.each do |deck| %>
	<%= form_for deck, :url => rounds_path, :html => { :method => :post} do |f| %>
		<%= hidden_field_tag(:deck_id, value=deck.id)%>
		<br>
		<%= f.submit deck.category %>
	<% end %>
	</li>

<% end %>
</ul>

app/views/rounds/show.html.erb
<h1> <%= @round_category  %> </h1>

<p>You've completed a round of <%= @round.deck.category %>. You answered <%= @first_try %> / <%= @total_questions %> cards correctly on the first try. You submitted <%= @total_guesses %> guesses before each card was answered correctly.</p>

<% if !logged_in? %>
  <% @round.guesses.delete_all %>
  <% @round.destroy %>
<% end %>

app/views/users/_errors.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Register') %>
<h1>Register</h1>

<%= render 'errors' %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= f.email_field :email, placeholder: "example@email.com" %>
      <%= f.password_field :password, placeholder: "password" %>

      <%= f.submit "Create my account" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="banner"><h2>Hello, <%= @user.email %>!</h2>

<h3>Scores:</h3>
<% if @rounds %>
<% @rounds.each do |round| %>
  <div id="scores">
  <h4>Quiz Name: <%= round.deck.category %></h4>
  <p>Date: <%= round.created_at %></p>
  <p>Cards in deck: <%= round.deck.cards.length %></p>
  <p>First Guess Correct: <%=round.first_guess %> </p>
  <p>Total Guesses: <%=round.guesses.length %> </p>
  </div>
  <br>
<% end %>
<% end %>


</div>